### ISSUE TITLE
Speed up the Development Process

### ISSUE THREAD

**Issue by zastrowm** [zastrowm/friendly-engine#6]
After the switch away from stencil.js (see #5), we lost a couple nice benefits like hot reload, TS decorators.  This issue serves as the milestone tracker for getting back the niceties that we lost.

- [X] Allow using JSX for defining elements (#7)
- [x] Implement hot-reload of elements (#13)
- [x] Add TS decorators to simplify custom elements (related to #10)

**Comment by zastrowm** [comment]
We never got hot reload of elements, but per #13, the full-page layout save/restore provides a sufficient experience.
